// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhD3km8GphfJaKvMFAn_mZZd_Z3Fxn_Q',
    appId: '1:896924972998:web:a9ea7c44365ac1b713a4c7',
    messagingSenderId: '896924972998',
    projectId: 'loja-7f072',
    authDomain: 'loja-7f072.firebaseapp.com',
    storageBucket: 'loja-7f072.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtf-p3-KR5vnQninvM2jxN7DrYqyJU7I',
    appId: '1:896924972998:android:66bc19f20ebdeabf13a4c7',
    messagingSenderId: '896924972998',
    projectId: 'loja-7f072',
    storageBucket: 'loja-7f072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAblKC3afp8C0VRRQPvIqMDxOtTSIFIGGM',
    appId: '1:896924972998:ios:465016d342e35c4c13a4c7',
    messagingSenderId: '896924972998',
    projectId: 'loja-7f072',
    storageBucket: 'loja-7f072.appspot.com',
    iosClientId: '896924972998-nl0lpbranl0hnkg4jqfd6bnbhr22vh3b.apps.googleusercontent.com',
    iosBundleId: 'br.com.toliu.loja',
  );

}